# Learn about numpy imporant function

## Numpy - Numerical python

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [3]:
a = np.array([[1,2,3,5],[6,7,8,9]])

In [13]:
# using type we can find the type of array.
type(a)

numpy.ndarray

In [4]:
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [6]:
# lets check thr dim ndim - dimension
a.ndim

2

In [9]:
# lets check the shape mean how may row and how many column shape(block, row, column)
# we can calculate how many rows and columns are present - shape  
a.shape

(2, 4)

In [10]:
# Using size we can find toltal element present in array
a.size

8

In [12]:
# using itemsize we can calculate the individual item byte size
a.itemsize

4

In [39]:
# by using size off we can check the total size of array in byte
a.__sizeof__()

160

In [17]:
#using len we can find the len of of a array.
len(a)

2

In [20]:
# data function will give the memory addresss in hex
a.data

In [21]:
# so we have some function so we can create the direct array.
# np.zeroes
# np.ones
# np.identity - create the diagonal matrix
# np.eye - also used to create the diagonal matrix
# 

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [24]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones(5,dtype='f8')

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [28]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# eye will be used to create the diagonal matrix
np.eye(3,dtype='bool')

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
~np.eye(3,dtype='bool')

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [41]:
# by using full we can create the numpy value as per we supplied
np.full((4,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
n = int('enter the no which you have to fill:')
np.full