# Learn about numpy imporant function

## Numpy - Numerical python

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [3]:
a = np.array([[1,2,3,5],[6,7,8,9]])

In [13]:
# using type we can find the type of array.
type(a)

numpy.ndarray

In [4]:
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [6]:
# lets check thr dim ndim - dimension
a.ndim

2

In [9]:
# lets check the shape mean how may row and how many column shape(block, row, column)
# we can calculate how many rows and columns are present - shape  
a.shape

(2, 4)

In [10]:
# Using size we can find toltal element present in array
a.size

8

In [12]:
# using itemsize we can calculate the individual item byte size
a.itemsize

4

In [39]:
# by using size off we can check the total size of array in byte
a.__sizeof__()

160

In [17]:
#using len we can find the len of of a array.
len(a)

2

In [20]:
# data function will give the memory addresss in hex
a.data

In [21]:
# so we have some function so we can create the direct array.
# np.zeroes
# np.ones
# np.identity - create the diagonal matrix
# np.eye - also used to create the diagonal matrix
# 

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [24]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones(5,dtype='f8')

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [28]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# eye will be used to create the diagonal matrix
np.eye(3,dtype='bool')

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
~np.eye(3,dtype='bool')

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [41]:
# by using full we can create the numpy value as per we supplied
np.full((4,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [6]:
n = int(input('enter no you want to fill:'))
np.full((3,3),fill_value=n)

enter no you want to fill:2


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
# arange:used to generate the sequuence of number
# start from 0 ends at n-1 and it will give the rangewise distribution of data like python range.
# start stop and step we are given in numpy.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# Default it will split the nu in 50 parts
# start and stop shoud given in the linspace
np.linspace(1,10)
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Shape manipulation:

In [12]:
# reshape:temp
# resize:permenent

In [15]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# In reshape -1 mean it will be select automatically by python
a.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# resize:
#it will create the permenent change.
a.resize(4,2)

In [19]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# If i want to convert the ND array to 1D array then we can use the ravel and flatten 

In [22]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
b = a.flatten()
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
print(len(b))

8


# Transpose is used to convert row to column and column to row

In [7]:
# transpose used to covert the row to column and column to row
# It is temp
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [8]:
a.transpose()

array([[1, 6],
       [2, 7],
       [3, 8],
       [5, 9]])

# Indexing and slicing over array 

In [9]:
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [10]:
a[0]

array([1, 2, 3, 5])

In [11]:
a[1]

array([6, 7, 8, 9])

In [12]:
a[0] = [10,11,12,14]

In [13]:
a

array([[10, 11, 12, 14],
       [ 6,  7,  8,  9]])

In [16]:
a[:,0] = [1,2]
a

array([[ 1, 11, 12, 14],
       [ 2,  7,  8,  9]])

In [2]:
b = np.array([[1,2,3,5],[5,6,9,8],[1,5,7,0]])
b

array([[1, 2, 3, 5],
       [5, 6, 9, 8],
       [1, 5, 7, 0]])

In [3]:
b[1:,1:-1]

array([[6, 9],
       [5, 7]])

In [4]:
b[0::2,2:]

array([[3, 5],
       [7, 0]])

In [5]:
b[::2,::3] = 0

In [6]:
b

array([[0, 2, 3, 0],
       [5, 6, 9, 8],
       [0, 5, 7, 0]])

# Adding and Removing Element: 
    append
    insert
    delete

In [12]:
np.append(b,[[0,0,0,0]],axis=0)

array([[0, 2, 3, 0],
       [5, 6, 9, 8],
       [0, 5, 7, 0],
       [0, 0, 0, 0]])

In [14]:
np.append(b,[[0],[0],[0]],axis=1)

array([[0, 2, 3, 0, 0],
       [5, 6, 9, 8, 0],
       [0, 5, 7, 0, 0]])

In [17]:
np.insert(b,1,[0,0,0,0],axis=0)

array([[0, 2, 3, 0],
       [0, 0, 0, 0],
       [5, 6, 9, 8],
       [0, 5, 7, 0]])

In [18]:
np.insert(b,2,[0,0,0],axis=1)

array([[0, 2, 0, 3, 0],
       [5, 6, 0, 9, 8],
       [0, 5, 0, 7, 0]])

In [19]:
np.delete(b,0,axis=0)

array([[5, 6, 9, 8],
       [0, 5, 7, 0]])

In [20]:
np.delete(b,0,axis=1)

array([[2, 3, 0],
       [6, 9, 8],
       [5, 7, 0]])

In [21]:
b

array([[0, 2, 3, 0],
       [5, 6, 9, 8],
       [0, 5, 7, 0]])

# Numpy important function: 

In [22]:
np.sort(b)

array([[0, 0, 2, 3],
       [5, 6, 8, 9],
       [0, 0, 5, 7]])

In [24]:
np.sort(b,axis=0)

array([[0, 2, 3, 0],
       [0, 5, 7, 0],
       [5, 6, 9, 8]])

In [25]:
b

array([[0, 2, 3, 0],
       [5, 6, 9, 8],
       [0, 5, 7, 0]])

In [31]:
np.split(b,3,axis=0)

[array([[0, 2, 3, 0]]), array([[5, 6, 9, 8]]), array([[0, 5, 7, 0]])]

In [33]:
a = np.copy(b)

In [34]:
print(id(a))
print(id(b))

2664351047184
2664186559152


In [35]:
# IT IS SHELLOW COPY wHERE same obj with diff id in both variable

In [39]:
c = a

In [40]:
print(id(a))
print(id(c))

2664351047184
2664351047184


In [41]:
# its called the deep copy where same object with same id