# Learn about numpy imporant function

## Numpy - Numerical python

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [3]:
a = np.array([[1,2,3,5],[6,7,8,9]])

In [13]:
# using type we can find the type of array.
type(a)

numpy.ndarray

In [4]:
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [6]:
# lets check thr dim ndim - dimension
a.ndim

2

In [9]:
# lets check the shape mean how may row and how many column shape(block, row, column)
# we can calculate how many rows and columns are present - shape  
a.shape

(2, 4)

In [10]:
# Using size we can find toltal element present in array
a.size

8

In [12]:
# using itemsize we can calculate the individual item byte size
a.itemsize

4

In [17]:
#using len we can find the len of of a array.
len(a)

2

In [20]:
# data function will give the memory addresss in hex
a.data

In [21]:
# so we have some function so we can create the direct array.

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [24]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])